Adding missing docstrings to all public functions.
bp/ResSimpy pull request #379
Opened 2024-08-20 15:13 UTC by MahmoudAlamar03

2024-08-21 12:25 UTC, jonnyh404 requested changes
Great work improving the code base by adding all these high quality docstrings. Please have a look at my comments and add those small changes. Otherwise looks good to me!

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/Nexus/NexusSimulator.py
> +        """Sets whether the runcontrol file will expand the include files with time cards in. Defaults to True."""
Is this really what this write_times does? If so we probably need to call it something slightly different!

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/OpenGoSim/Model_Parts/OpenGoSimNetwork.py
> +        """Returns."""
"""Loads the OpenGoSimNetwork. Not Implemented Yet."""

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/OpenGoSim/OpenGoSimSimulator.py
> +        """Returns"""
Returns final date in the simulator.

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/OpenGoSim/OpenGoSimSimulator.py
> +        """Returns an instance of OpenGo simulation type."""
OpenGoSim

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/OpenGoSim/OpenGoSimSimulator.py
> +    @staticmethod
Remove additional staticmethod decorator.

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/OperationsMixin.py
> +        """Returns"""
Returns table header as a string

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/Wells.py
> +        """?
Gets a well by well name

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/Wells.py
> +        """Returns a pandas data frame."""
Returns wells as a pandas dataframe

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/Wells.py
> +        """?
Modifies a completion in a named well using a list of properties. How enum determines if the completions are added, removed or modified.

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/Wells.py
> +            how (OperationEnum) : ?
Check the OperationEnum for valid options.

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/Wells.py
> +            completion_properties_list (list[dict[str, None | float | int | str]]) : ?
List of completions property dictionaries to pass through to each of the ADD/REMOVE/MODIFY operations.

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/Wells.py
> +            preserve_previous_completions():? .
When adding new completions to a new date we can either... Simply add the completion on its own, effectively removing all previous completions or we can add it with the previous set of completions at the new timestep. 
This bool toggles that behaviour.

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/Wells.py
> +            well_name(str): Well name.
Well name to remove the completion from.

2024-08-21 12:25 UTC, jonnyh404 commented on ResSimpy/Wells.py
> +            well_name (str): Well name.
Well name to modify completion from.

2024-08-21 12:25 UTC, jonnyh404 commented on pyproject.toml
> +    "D100", "D103", "D101", "D205", # Docstrings
Great work improving the codebase and enabling this rule.

2024-08-22 12:01 UTC, cflynn3 commented on ResSimpy/Completion.py
> +        """Returns the location of the well as a float."""
location of the completion in the x direction. Same for others below.

2024-08-27 10:03 UTC, jonnyh404 approved these changes
Looks good to me. Thanks for making the changes.

2024-08-27 10:03 UTC, merged