Properties_dict to named parameters
bp/ResSimpy pull request #400
Opened 2024-10-15 12:24 UTC by MahmoudAlamar03

Draft PR for a quick check before applying conversion to the rest of the files.

2024-10-24 14:23 UTC, jonnyh404 requested changes
Looks good to me so far, would like to see if you can pass more of the attributes through to the base classes and implement a test to ensure that the pass through of attributes works as intended!

2024-10-24 14:23 UTC, jonnyh404 commented on ResSimpy/Nexus/DataModels/Network/NexusConstraint.py
>          super().__init__(_date_format=date_format, _start_date=start_date, _unit_system=unit_system, name=name)
The overlapping attributes with the base class could be passed through here to ensure that they are set on the base rather than the child class

2024-10-24 14:23 UTC, jonnyh404 commented on ResSimpy/Nexus/DataModels/Network/NexusNodeConnection.py
>          super().__init__(date_format=date_format, start_date=start_date, unit_system=unit_system, name=name, date=date,
Should these also get passed through to the base class if they overlap?

2024-10-24 14:23 UTC, jonnyh404 commented on tests/Nexus/nexus_simulator/test_nexus_constraints.py
> +                                                   date_format=DateFormat.DD_MM_YYYY,
Can you update this test to use your newly written code. Instead of using a properties dict can you make it so they use the named attributes that you've created. 

e.g. `well_2_expected_constraint_2 = NexusConstraint(date='15/10/2024', name='well_2', max_surface_liquid_rate=4567, date_format=DateFormat.DD_MM_YYYY, unit_system=UnitSystem.ENGLISH, 
start_date=start_date)`

2024-10-25 14:28 UTC, cflynn3 commented on ResSimpy/DataModelBaseClasses/Constraint.py
> -    max_avg_comp_dp: Optional[float] = None
They should be removed from the derived classes, not the base class.

2024-10-25 14:35 UTC, cflynn3 commented on ResSimpy/Nexus/DataModels/Network/NexusConstraint.py
>          super().__init__(_date_format=date_format, _start_date=start_date, _unit_system=unit_system, name=name)
The overlapping attributes should have been deleted from the child class rather than the parent.

2024-10-25 14:46 UTC, cflynn3 commented on ResSimpy/Nexus/DataModels/Network/NexusWellhead.py
>          super().__init__(date_format=date_format, start_date=start_date, unit_system=unit_system, name=name, date=date,
Please also pass through the base class properties.

2024-10-25 14:47 UTC, cflynn3 reviewed
Some good changes here. Please look at the suggestions posted and let me know once you've made further changes.

2024-10-27 21:22 UTC, MahmoudAlamar03 commented on ResSimpy/DataModelBaseClasses/Constraint.py
> -    max_avg_comp_dp: Optional[float] = None
oops, meant to remove them from the child class rather than the parent class.

2024-10-27 23:35 UTC, MahmoudAlamar03 commented on ResSimpy/Nexus/DataModels/Network/NexusWellhead.py
>          super().__init__(date_format=date_format, start_date=start_date, unit_system=unit_system, name=name, date=date,
Done

2024-10-29 01:25 UTC, MahmoudAlamar03 commented on ResSimpy/Nexus/DataModels/Network/NexusNodeConnection.py
>          super().__init__(date_format=date_format, start_date=start_date, unit_system=unit_system, name=name, date=date,
Done

2024-10-30 00:10 UTC, MahmoudAlamar03 commented on tests/Nexus/nexus_simulator/test_nexus_constraints.py
> +                                                   date_format=DateFormat.DD_MM_YYYY,
done

2024-10-30 10:11 UTC, jonnyh404 approved these changes
Good changes! Looks good to me.

2024-10-30 11:28 UTC, cflynn3 approved these changes
Looks good to me.

2024-10-30 11:28 UTC, merged